const cloudinary = require('cloudinary').v2;
require('dotenv').config();
// var fs = require('fs');

// Configuration
cloudinary.config({
  cloud_name: process.env.CLOUDINARY_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_SECRET,
  secure: true,
});

var uploads = {};

cloudinary.uploader
  .upload('../mock_sample_packs/mp3/kicks/Kick, Dubstep Var 10.mp3', {
    resource_type: 'video',
    public_id: 'folderName/kick_dubstep_var_10',
  })
  .then((result) => {
    console.log(result);
  })
  .catch((error) => {
    console.log(error);
  });

// File upload
// cloudinary.uploader.upload(
//   './pizza.jpg',
//   { tags: 'basic_sample' },
//   (err, image) => {
//     console.log();
//     console.log('** File Upload');
//     if (err) {
//       console.warn(err);
//     }
//     console.log(
//       "* public_id for the uploaded image is generated by Cloudinary's service."
//     );
//     console.log('* ' + image.public_id);
//     console.log('* ' + image.url);
//   }
// );

function waitForAllUploads(id, err, image) {
  uploads[id] = image;
  var ids = Object.keys(uploads);
  if (ids.length === 6) {
    console.log();
    console.log('**  uploaded all files (' + ids.join(',') + ') to cloudinary');
  }
}

/* 
// Upload
const res = cloudinary.uploader.upload(
  'https://upload.wikimedia.org/wikipedia/commons/a/ae/Olympic_flag.jpg',
  { public_id: 'olympic_flag' }
);

res
  .then((data) => {
    console.log(data);
    console.log(data.secure_url);
  })
  .catch((err) => {
    console.log(err);
  });

// Generate
const url = cloudinary.url('olympic_flag', {
  width: 100,
  height: 150,
  Crop: 'fill',
});

// The output url
console.log(url);
// https://res.cloudinary.com/<cloud_name>/image/upload/h_150,w_100/olympic_flag 
*/
